on:
  push:
    branches:
      - main

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: Yamada-Ika/norminette-action@v3
      with:
        flags: '.'
